
substitutions:
  account:            "Demo Customer"
  startdate:          "Current_Date - 31"
  enddate:            "Current_Date - 1"
  td_quicklook:       "sh186014"

transcend:
  host:       "tdprdcop3.td.teradata.com"
  logmech:    "LDAP"
  username:   "{tdusername}"
  password:   "{tdpassword}"
  db_coa:     "adlste_coa"
  db_region:  "adlste_westcomm"

folders:
  override:  "0_override"
  download:  "1_download"
  sql:       "2_sql_store"
  run:       "3_ready_to_run"
  output:    "4_output"

settings:
  githost:       "https://raw.githubusercontent.com/tdcoa/sql/master/"
  gitfileset:    "filesets/filesets.yaml"
  gitmotd:       "motd.txt"
  localfilesets: "./{download}/filesets.yaml"
  skip_git:      "False"
  skip_dbs:      "False"
  ignore_error_codes: [123,456,789] # TBD
  run_non_fileset_folders: "True"
  customer_connection_type: "sqlalchemy"  # "sqlalchemy" or name of ODBC driver
